spring:
  application:
    name: sob-blog
  datasource:
    url: jdbc:mysql://192.168.6.133:3306/sob_blog_system?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
  jpa:
    show-sql: true
  data:
    solr:
      host: http://192.168.6.133:8983/solr/sob_blog_core
  redis:
    host: 192.168.6.133 # Redis服务器地址
    port: 6379 # Redis服务器连接端口
    password: 123456 # Redis服务器连接密码



server:
  port: 2020

sob.blog.image.save-path: D:\Intellij Docu\sob-blog-image-data
#2MB
sob.blog.image.max-size: 2097152
#控制swagger 开关
sob.blob.swagger.enable: true